server {
    listen 443 ssl;
    server_name comments.noda.co.nz;

    ssl_certificate /etc/nginx/ssl/noda.dev.crt;
    ssl_certificate_key /etc/nginx/ssl/noda.dev.key;

    location / {
        proxy_pass http://remark42:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
